### PR TITLE
fix(lib): fixed check for recent worklog

### LINKED ISSUE #152: Recent worklog fix is broken

### PR DESCRIPTION
**Pull request by dspasojevic**
fix #152

### CODE REVIEW

File: lib/src/services/test_data/issue_data.ts [hunk 1]
```diff
@@ -64,3 +64,12 @@ export const enhancedIssue: EnhancedIssue = {
   quality: "A",
   qualityReason: "for a good reason",
 };
+
+export const worklog: IssueWorklog = {
+  author: {
+    name: "danixon",
```
Comment (danielnixon) [inline lib/src/services/test_data/issue_data.ts:70]: I'm famous

**Review by danielnixon — APPROVED** [review]
